export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_DIAMOND_AND_HEART = "GET_DIAMOND_AND_HEART";
export const GET_ALL_USERS_SCORE = "GET_ALL_USERS_SCORE";
